### ISSUE TITLE
Ability to Rename Ring of Shadows

### ISSUE THREAD

**Issue by SandroVA** [LlemonDuck/easy-teleports#12]
This would help a lot instead of remembering what area belongs to what boss.

**Comment by LlemonDuck** [comment]
Supported in e1bec1b5c87f31cbfe55fa13d04715012abcab3a (with colour!) 
![image](https://github.com/LlemonDuck/easy-teleports/assets/1868974/e08ee265-102f-4726-bce8-fe2f3541970c)

**Comment by SandroVA** [comment]
So many Updates @LlemonDuck fantastic work! 

One small issue: 
- If you left click the right of shadows teleport "The" is not colored in "The DT2 Vault"

Also would it at all be possible to make the color change when hovering over the options? 
https://github.com/LlemonDuck/easy-teleports/assets/7264387/4e0ea297-e261-4176-8810-83d59e4ac2ee
