### ISSUE TITLE
Kharedst Memoirs / Book of the Dead does not replace on dialog options

### ISSUE THREAD

**Issue by LlemonDuck** [LlemonDuck/easy-teleports#14]
When using "Reminisce" the options are not replaced. They have different text than the equipped options.

**Comment by LlemonDuck** [comment]
Supported in 908040c35e55c18236d9708db1cc92f0883feb26

**Comment by JWannet** [comment]
> When using "Reminisce" the options are not replaced. They have different text than the equipped options.

Hi, could you reenable this 'bug' as an optional setting? I got quite used to the option not being coloured when I 'Reminisce' from the book, but really like the colouring when I have the book equipped. 
So an optional setting to have these two different, would be amazing :)
