### ISSUE TITLE
Suggestion: Fairy mushroom league relic item teleports rename/remove

### ISSUE THREAD

**Issue by Codadragon** [LlemonDuck/easy-teleports#19]
Hi there, I love your plugin; if you have time, would you be willing to add the ability to rename or remove visibility for the Tool Leprechauns and Spirit Trees teleport options? Players in the league will only have access to some league areas and, therefore, will have many teleport options displayed that are irrelevant to them. 

If it is not possible to toggle remove the unusable/irrelevant teleports, would it be possible to rename them to an invisible character so they cannot be clicked? Thanks for the plugin! Keep up the great work!

**Comment by LlemonDuck** [comment]
Better Teleport Menu does this already, I highly recommend it

https://runelite.net/plugin-hub/show/better-teleport-menu

**Comment by Codadragon** [comment]
I did not know that! Thank you very much! <3
