### ISSUE TITLE
Book of the dead Oversight

### ISSUE THREAD

**Issue by BuzzfeedBlue** [LlemonDuck/easy-teleports#4]
Once you have finished the questline involving Kharedsts Memoirs, the item becomes the Book of the Dead and the plugin no longer recognizes it. The teleport menu reverts back to the vanilla entries at that point.

**Comment by LlemonDuck** [comment]
I accounted for the Book of the Dead already: 
![image](https://user-images.githubusercontent.com/1868974/192428929-b8a1ee2b-4fcf-4946-b9de-c01f46b09ea3.png)

If you mean the chat dialog, that one isn't supported on either book since I felt it was descriptive enough already.
