### ISSUE TITLE
REQUEST: Achievement Diary Cape Teleport Names

### ISSUE THREAD

**Issue by FeAspers** [LlemonDuck/easy-teleports#7]
I would love to see these get a rename, as it stands they are somewhat recognizable but would love to easily understand them better.
**Possible Name Suggestion:**
**1.)** Ardougne Bar (Two-pints)
**2.)** Shanty Pass (Jarr)
**3.)** Falador Castle (Sir Rebral)
**4.)** Rellekka POH (Thorodin)
**5.)** Camelot Flax Keeper
**6.)** Agility Arena (Jackie)
**7.)** Shilo Village
**8.)** Shilo Village: Jungle Entrance
**9.)** TzHaar City
**A.)** Xeric's Heart (Elise)
**B.)** Lumbridge
**C.)** Canifis (Le-sabrè)
**D.)** Varrock (Toby)
**E.)** Edgeville (Lesser Fanatic)
**F.)** Gnome Stronghold (Gnome Child)
**G.)** Draynor Village (Twiggy O'Korn)
![image](https://user-images.githubusercontent.com/73009020/197406573-fe11ba21-4b06-4015-be5d-159cff589a7e.png)
![image](https://user-images.githubusercontent.com/73009020/197406582-2fb8c715-4082-481e-a1fe-ce4b3f6b81a5.png)

**Comment by LlemonDuck** [comment]
Supported in 54dbbd414fe534ae24558d6c0682822f023afae3
